version: '3.4'

services:
  webmvc:
    image: ${DOCKER_REGISTRY-}webmvc
    build:
      context: .
      dockerfile: WebApps/WebMVC/Dockerfile

  identityservice-api:
    image: ${DOCKER_REGISTRY-}identityserviceapi
    build:
      context: .
      dockerfile: Services/Identity/IdentityService.API/Dockerfile

  catalogservice-api:
    image: ${DOCKER_REGISTRY-}catalogserviceapi
    build:
      context: .
      dockerfile: Services/Catalog/CatalogService.API/Dockerfile


  cartservice-api:
    image: ${DOCKER_REGISTRY-}cartserviceapi
    build:
      context: .
      dockerfile: Services/Cart/CartService.API/Dockerfile


  paymentservice-api:
    image: ${DOCKER_REGISTRY-}paymentserviceapi
    build:
      context: .
      dockerfile: Services/Payment/PaymentService.API/Dockerfile


  orderservice-api:
    image: ${DOCKER_REGISTRY-}orderserviceapi
    build:
      context: .
      dockerfile: Services/Orders/OrderService.API/Dockerfile


  marketingservice-api:
    image: ${DOCKER_REGISTRY-}marketingserviceapi
    build:
      context: .
      dockerfile: Services/Marketing/MarketingService.API/Dockerfile


  web-gtw:
    image: ${DOCKER_REGISTRY-}webgtw
    build:
      context: .
      dockerfile: ApiGateWays/Web/Web.Gtw/Dockerfile


  apigtw-loadbalancer:
    image: ${DOCKER_REGISTRY-}apigtwloadbalancer
    build:
      context: .
      dockerfile: ApiGateWays/LoadBalancer/ApiGtw.LoadBalancer/Dockerfile

