version: '3.4'

services:
  webmvc:
    image: ${DOCKER_REGISTRY-}webmvc
    build:
      context: .
      dockerfile: WebApps/WebMVC/Dockerfile

  identityservice.api:
    image: ${DOCKER_REGISTRY-}identityserviceapi
    build:
      context: .
      dockerfile: IdentityService.API/Dockerfile

  catalogservice.api:
    image: ${DOCKER_REGISTRY-}catalogserviceapi
    build:
      context: .
      dockerfile: CatalogService.API/Dockerfile


  cartservice.api:
    image: ${DOCKER_REGISTRY-}cartserviceapi
    build:
      context: .
      dockerfile: CartService.API/Dockerfile


  paymentservice.api:
    image: ${DOCKER_REGISTRY-}paymentserviceapi
    build:
      context: .
      dockerfile: PaymentService.API/Dockerfile


  orderservice.api:
    image: ${DOCKER_REGISTRY-}orderserviceapi
    build:
      context: .
      dockerfile: OrderService.API/Dockerfile


  marketingservice.api:
    image: ${DOCKER_REGISTRY-}marketingserviceapi
    build:
      context: .
      dockerfile: MarketingService.API/Dockerfile


  web.gtw:
    image: ${DOCKER_REGISTRY-}webgtw
    build:
      context: .
      dockerfile: ApiGateWays/Web/Web.Gtw/Dockerfile

